import express from 'express';
import crypto from 'crypto';
import { query } from './database.js';
const router=express.Router();
let tableReady=null;
const clean=v=>String(v??'').trim(); const money=v=>Number(v);
const hashValue=v=>crypto.createHash('sha256').update(String(v)).digest('hex');
function cookies(req){const out={};for(const part of String(req.headers.cookie||'').split(';')){const i=part.indexOf('=');if(i<0)continue;const k=part.slice(0,i).trim(),v=part.slice(i+1).trim();try{out[k]=decodeURIComponent(v);}catch{out[k]=v;}}return out;}
async function ensureTable(){if(!tableReady){tableReady=query(`
CREATE TABLE IF NOT EXISTS expenses(id SERIAL PRIMARY KEY,owner_id INTEGER NOT NULL,property_id INTEGER,expense_date DATE NOT NULL DEFAULT CURRENT_DATE,category VARCHAR(100) NOT NULL DEFAULT 'Other',amount NUMERIC(12,2) NOT NULL CHECK(amount>0),note TEXT DEFAULT '',created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP);
ALTER TABLE expenses ADD COLUMN IF NOT EXISTS property_id INTEGER;
ALTER TABLE expenses ADD COLUMN IF NOT EXISTS expense_date DATE NOT NULL DEFAULT CURRENT_DATE;
ALTER TABLE expenses ADD COLUMN IF NOT EXISTS category VARCHAR(100) NOT NULL DEFAULT 'Other';
ALTER TABLE expenses ADD COLUMN IF NOT EXISTS amount NUMERIC(12,2) NOT NULL DEFAULT 0;
ALTER TABLE expenses ADD COLUMN IF NOT EXISTS note TEXT DEFAULT '';
ALTER TABLE expenses ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP;
DO $$
DECLARE c RECORD;
BEGIN
FOR c IN SELECT con.conname FROM pg_constraint con JOIN pg_class rel ON rel.oid=con.conrelid JOIN pg_attribute att ON att.attrelid=rel.oid AND att.attnum=ANY(con.conkey) WHERE rel.relname='expenses' AND con.contype='f' AND att.attname='owner_id'
LOOP EXECUTE format('ALTER TABLE expenses DROP CONSTRAINT IF EXISTS %I',c.conname); END LOOP;
END $$;
CREATE INDEX IF NOT EXISTS idx_expenses_owner_date ON expenses(owner_id,expense_date);
CREATE INDEX IF NOT EXISTS idx_expenses_owner_property ON expenses(owner_id,property_id);`).catch(e=>{tableReady=null;throw e;});}return tableReady;}
async function syncMaintenanceExpenses(ownerId){try{await query(`INSERT INTO expenses(owner_id,property_id,expense_date,category,amount,note,created_at)
SELECT m.owner_id,m.property_id,COALESCE(m.due_date,m.created_at::date),'Maintenance',m.actual_cost,'[maintenance:'||m.id::text||'] '||COALESCE(NULLIF(m.category,''),'General')||': '||COALESCE(m.description,''),COALESCE(m.created_at,CURRENT_TIMESTAMP)
FROM maintenance_tickets m WHERE m.owner_id=$1 AND COALESCE(m.actual_cost,0)>0 AND NOT EXISTS(SELECT 1 FROM expenses e WHERE e.owner_id=m.owner_id AND e.category='Maintenance' AND (e.note LIKE '[maintenance:'||m.id::text||']%' OR e.note=COALESCE(NULLIF(m.category,''),'General')||': '||COALESCE(m.description,'')))`,[ownerId]);}catch(e){if(!/maintenance_tickets.*does not exist/i.test(String(e?.message||'')))throw e;}}
async function requireOwner(req,res,next){try{const token=cookies(req).peacely_session;if(!token)return res.status(401).json({success:false,error:'Authentication required.'});const r=await query(`SELECT o.id,o.name,o.email FROM sessions s INNER JOIN owners o ON o.id=s.owner_id WHERE s.token_hash=$1 AND s.expires_at>CURRENT_TIMESTAMP LIMIT 1`,[hashValue(token)]);if(!r.rows.length)return res.status(401).json({success:false,error:'Authentication required.'});req.expenseOwner=r.rows[0];return next();}catch(e){console.error('Expense auth failed:',e);return res.status(500).json({success:false,error:'Unable to access expenses.'});}}
const validDate=v=>/^\d{4}-\d{2}-\d{2}$/.test(clean(v));
async function propertyForOwner(ownerId,propertyId){if(propertyId===null||propertyId===undefined||propertyId==='')return null;const id=Number(propertyId);if(!Number.isInteger(id)||id<1)throw new Error('Invalid property.');const r=await query(`SELECT id,name FROM properties WHERE id=$1 AND owner_id=$2 LIMIT 1`,[id,ownerId]);if(!r.rows.length)throw new Error('Selected property was not found.');return r.rows[0];}
router.get('/expenses',requireOwner,async(req,res)=>{try{const ownerId=req.expenseOwner.id;const month=clean(req.query.month),propertyId=clean(req.query.property_id),params=[ownerId],where=['e.owner_id=$1'];if(month){if(!/^\d{4}-\d{2}$/.test(month))return res.status(400).json({success:false,error:'Month must be YYYY-MM.'});params.push(`${month}-01`);where.push('e.expense_date >= $2::date');where.push("e.expense_date < ($2::date + INTERVAL '1 month')");}if(propertyId){const id=Number(propertyId);if(!Number.isInteger(id)||id<1)return res.status(400).json({success:false,error:'Invalid property.'});params.push(id);where.push(`e.property_id=$${params.length}`);}const r=await query(`SELECT e.id,e.property_id,p.name AS property_name,e.expense_date,e.category,e.amount,e.note,e.created_at,e.created_at AS updated_at FROM expenses e LEFT JOIN properties p ON p.id=e.property_id AND p.owner_id=e.owner_id WHERE ${where.join(' AND ')} ORDER BY e.expense_date DESC,e.id DESC`,params);return res.json({expenses:r.rows});}catch(e){console.error('Expense list failed:',e);return res.status(500).json({success:false,error:e.message||'Unable to load expenses.'});}});
router.get('/expenses/summary',requireOwner,async(req,res)=>{try{const ownerId=req.expenseOwner.id;const month=clean(req.query.month),params=[ownerId],where=['e.owner_id=$1'];if(month){if(!/^\d{4}-\d{2}$/.test(month))return res.status(400).json({success:false,error:'Month must be YYYY-MM.'});params.push(`${month}-01`);where.push('e.expense_date >= $2::date');where.push("e.expense_date < ($2::date + INTERVAL '1 month')");}const totals=await query(`SELECT COALESCE(SUM(e.amount),0) AS total,COUNT(*)::INTEGER AS count FROM expenses e WHERE ${where.join(' AND ')}`,params);const categories=await query(`SELECT e.category,COALESCE(SUM(e.amount),0) AS amount,COUNT(*)::INTEGER AS count FROM expenses e WHERE ${where.join(' AND ')} GROUP BY e.category ORDER BY amount DESC`,params);const months=await query(`SELECT TO_CHAR(DATE_TRUNC('month',e.expense_date),'YYYY-MM') AS month,COALESCE(SUM(e.amount),0) AS amount,COUNT(*)::INTEGER AS count FROM expenses e WHERE e.owner_id=$1 AND e.expense_date>=DATE_TRUNC('month',CURRENT_DATE)-INTERVAL '11 months' GROUP BY DATE_TRUNC('month',e.expense_date) ORDER BY month DESC`,[ownerId]);return res.json({success:true,total:Number(totals.rows[0]?.total||0),count:Number(totals.rows[0]?.count||0),categories:categories.rows.map(r=>({...r,amount:Number(r.amount||0)})),months:months.rows.map(r=>({...r,amount:Number(r.amount||0)}))});}catch(e){console.error('Expense summary failed:',e);return res.status(500).json({success:false,error:'Unable to load expense summary.'});}});
router.post('/expenses',requireOwner,async(req,res)=>{try{const ownerId=req.expenseOwner.id,expenseDate=clean(req.body?.expense_date||req.body?.date),category=clean(req.body?.category)||'Other',amount=money(req.body?.amount),note=clean(req.body?.note||req.body?.notes),propertyId=req.body?.property_id===''||req.body?.property_id===undefined?null:req.body?.property_id;if(!validDate(expenseDate))return res.status(400).json({success:false,error:'Expense date must be YYYY-MM-DD.'});if(!Number.isFinite(amount)||amount<=0)return res.status(400).json({success:false,error:'Expense amount must be greater than zero.'});if(category.length>100)return res.status(400).json({success:false,error:'Expense category is too long.'});const property=await propertyForOwner(ownerId,propertyId);const r=await query(`INSERT INTO expenses(owner_id,property_id,expense_date,category,amount,note) VALUES($1,$2,$3,$4,$5,$6) RETURNING id,owner_id,property_id,expense_date,category,amount,note,created_at`,[ownerId,property?.id||null,expenseDate,category,amount,note]);return res.status(201).json({...r.rows[0],property_name:property?.name||null,updated_at:r.rows[0]?.created_at||null});}catch(e){console.error('Expense create failed:',e);return res.status(500).json({success:false,error:e.message||'Unable to create expense.'});}});
router.put('/expenses/:id',requireOwner,async(_req,res)=>res.status(403).json({success:false,error:'Expenses are permanent and cannot be edited.'}));
router.delete('/expenses/:id',requireOwner,async(_req,res)=>res.status(403).json({success:false,error:'Expenses are permanent and cannot be deleted.'}));
export default router;
